-- Create schema SAT
create extension if not exists pgcrypto;

create table if not exists clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  direccion text,
  telefono text,
  email text,
  created_at timestamp with time zone default now()
);

create table if not exists equipos (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid references clientes(id) on delete cascade,
  nombre text not null,
  marca text,
  modelo text,
  numero_serie text,
  ultima_revision date
);

create table if not exists tecnicos (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  especialidad text,
  activo boolean default true
);

create table if not exists ordenes_trabajo (
  id uuid primary key default gen_random_uuid(),
  numero_ticket bigint generated by default as identity,
  cliente_id uuid references clientes(id),
  equipo_id uuid references equipos(id),
  tecnico_id uuid references tecnicos(id),
  descripcion_averia text not null,
  tareas_realizadas text,
  tiempo_empleado_minutos integer,
  estado text default 'pendiente' check (estado in ('pendiente', 'en_proceso', 'pausado', 'finalizado')),
  prioridad text default 'media' check (prioridad in ('baja', 'media', 'alta', 'urgente')),
  foto_url text,
  firma_url text,
  fecha_inicio timestamp with time zone default now(),
  fecha_fin timestamp with time zone,
  localizacion_inicio text,
  localizacion_fin text
);

create table if not exists materiales_orden (
  id uuid primary key default gen_random_uuid(),
  orden_id uuid references ordenes_trabajo(id) on delete cascade,
  nombre_material text not null,
  cantidad integer default 1,
  precio_unitario decimal(10,2)
);

-- RLS de desarrollo (abierto)
alter table clientes enable row level security;
alter table equipos enable row level security;
alter table tecnicos enable row level security;
alter table ordenes_trabajo enable row level security;
alter table materiales_orden enable row level security;

drop policy if exists "dev_full_clientes" on clientes;
create policy "dev_full_clientes" on clientes for all to anon, authenticated using (true) with check (true);

drop policy if exists "dev_full_equipos" on equipos;
create policy "dev_full_equipos" on equipos for all to anon, authenticated using (true) with check (true);

drop policy if exists "dev_full_tecnicos" on tecnicos;
create policy "dev_full_tecnicos" on tecnicos for all to anon, authenticated using (true) with check (true);

drop policy if exists "dev_full_ordenes" on ordenes_trabajo;
create policy "dev_full_ordenes" on ordenes_trabajo for all to anon, authenticated using (true) with check (true);

drop policy if exists "dev_full_materiales" on materiales_orden;
create policy "dev_full_materiales" on materiales_orden for all to anon, authenticated using (true) with check (true);
